=== badtechnologies/bpl/bpl.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "author": {
      "type": "string"
    },
    "binaries": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "setupScripts": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "homepage": {
      "type": "string",
      "format": "uri"
    },
    "license": {
      "type": "string"
    },
    "shellVersion": {
      "type": "string",
      "pattern": "^(\\*|\\^?\\d+\\.\\d+\\.\\d+|~\\d+\\.\\d+\\.\\d+|>=?\\d+\\.\\d+\\.\\d+|<=?\\d+\\.\\d+\\.\\d+)$"
    },
    "dependencies": {
      "$ref": "#/definitions/dependencyMap"
    },
    "pythonDependencies": {
      "$ref": "#/definitions/dependencyMap"
    }
  },
  "required": [
    "name",
    "id",
    "version",
    "author",
    "shellVersion"
  ],
  "definitions": {
    "dependencyMap": {
      "type": "object",
      "propertyNames": {
        "pattern": "^[a-z0-9-]+$"
      },
      "additionalProperties": {
        "type": "string",
        "pattern": "^(\\*|\\^?\\d+\\.\\d+\\.\\d+|~\\d+\\.\\d+\\.\\d+|>=?\\d+\\.\\d+\\.\\d+|<=?\\d+\\.\\d+\\.\\d+)$"
      }
    }
  }
}

=== badtechnologies/bpl/lib/bssh/bpl.json
{
  "name": "BadBandSSH",
  "id": "bssh",
  "version": "0.10.2",
  "author": "Logan Dhillon",
  "homepage": "https://github.com/badtechnologies/bdsh/blob/main/docs/bssh.md",
  "binaries": {
    "bssh": "bssh.py"
  },
  "pythonDependencies": {
    "paramiko": "~5.0.0"
  },
  "setupScripts": [
    "setup.py"
  ],
  "shellVersion": "^0.5.0"
}
